### ISSUE TITLE
Resize method within image class

### ISSUE THREAD

**Issue by maestrotf** [LEX2016WoKaGru/pyclamster#19]
Due to memory and calculation power consumption, we need a method to resize the image with its coordinates.

**Comment by nobodyinperson** [comment]
This means, 2-dimensional interpolation is needed. Maybe [scipy.interpolate.interp2d] (http://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp2d.html#scipy.interpolate.interp2d) is appropriate for this task.

**Comment by maestrotf** [comment]
A possibility  is to use [scipy.misc.imresize](http://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imresize.html). It has everything we need. With this method we could use different interpolation schemes and could manage the PIL mode.

**Comment by nobodyinperson** [comment]
Calibration can now output scaled Coordinates, making the resize method not so important anymore.
Stalled.
