### ISSUE TITLE
LEX prerequisites

### ISSUE THREAD

**Issue by nobodyinperson** [LEX2016WoKaGru/pyclamster#20]
These steps **must** be completed **before** the LEX begins:

- [x] camera calibration working correctly
- [x] fisheye distortion working correctly
- [x] cloud detection working correctly
- [x] cloud matching working correctly
- [ ] height detection working correctly
- [ ] wind speed determination working correctly
- [ ] cloud cover determination working correctly

Eventually and the most important:

- [x] synthesis of all steps mentioned above to an **operational system**

Furthermore:

- [x] set up a **raspberry pi** to periodically **save camera images** for field sites

**Comment by maestrotf** [comment]
I've created a remote branch for changes concerning the **operational** use of pyclamster at the LEX2016. 
I've added three scripts (at the moment empty). The first is for the manual calibration of the cameras with the sun. The second is for the operational workflow within one timestep. And the last, but not least is for the temporal development and merging of clouds.

**Comment by nobodyinperson** [comment]
LEX is over...
