### ISSUE TITLE
implement cloud clustering

### ISSUE THREAD

**Issue by nobodyinperson** [LEX2016WoKaGru/pyclamster#6]

**Comment by maestrotf** [comment]
The script for the unsupervised generation of training data with the k-means is finished. 
Next step will be the implementation of an Extreme Learning Machine based neural network for supervised learning.

**Comment by maestrotf** [comment]
The k-means algorithm is implemented with a automatic cluster finding method. The cluster finding method is slow and the algorithm isn't tested for cloud clustering so this issue remains open.

**Comment by maestrotf** [comment]
In the basic solution the clouds are clustered together, if there is a connection between the clouds. 
So for Version 0.1-dev this issue will be closed and a new enhancement issue will be opened.
