### ISSUE TITLE
implement cloud position/height locating

### ISSUE THREAD

**Issue by nobodyinperson** [LEX2016WoKaGru/pyclamster#9]
Simple stereo (Doppelanschnitt)

**Comment by maestrotf** [comment]
Due to the fact this is one of the final steps which are needed to perform a basic stereo analysis of cloud images, this issue should have a milestone (like beta, 0.5)

**Comment by maestrotf** [comment]
The formulas for the cloud locating are inserted. But the need to be checked.

**Comment by nobodyinperson** [comment]
Done.
